apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/simple_app:IMAGEVERSION
        name: single-app
        ports:
        - containerPort: 5000
        resources: {}
status: {}
